services:
  homework-tests:
    build:
      context: ../../..
      dockerfile: 01-intro-and-kinematics/homework/container/Dockerfile
    volumes:
      - ../../..:/app:ro
      - ../../../dev/01-intro-and-kinematics/homework/reference_solution:/app/01-intro-and-kinematics/homework/reference_solution:ro
      - ../../../dev/01-intro-and-kinematics/homework/hidden_tests:/app/01-intro-and-kinematics/homework/hidden_tests:ro
    working_dir: /app/01-intro-and-kinematics/homework
